### ISSUE TITLE
Override default mustache templates

### ISSUE THREAD

**Issue by mpelzsherman** [kezoo/sprite-webpack-plugin#10]
Hi,

Is there any way to override the default mustache templates?

Many thanks!

**Comment by jjalonso** [comment]
No answers here?

I saw is hardcoded in templates/sprite.js

**Comment by peeyushsrivastava** [comment]
This is really needed feature, I want to use custom template format in this plugin. How can I configure it with this plugin.

**Comment by mpelzsherman** [comment]
@peeyushsrivastava - You can give #11 a try.

**Comment by kezoo** [comment]
New option "templatePath", please try it see if your problems could be solved. 
[427fcc77d52cff20d48a469ea0a927b8b27cbed1](https://github.com/kezoo/sprite-webpack-plugin/commit/427fcc77d52cff20d48a469ea0a927b8b27cbed1)
