### ISSUE TITLE
Change the sprite path in a less/scss

### ISSUE THREAD

**Issue by pionl** [kezoo/sprite-webpack-plugin#13]
Hi,

when I export the less I use it in the context of the src dir (then I import it in my style.less). Because of this the url to the sprite will be incorrect in the final build. 

We should be apple to set a custom path to the sprite that would give us all more flexible approach.

Also would be great to add a hash support.

Thank you for the package 👍 

P.S: Similar settings are implemented in [glue](https://github.com/jorgebastida/glue)

**Comment by kezoo** [comment]
Yes, the path should be smarter, like you can define your own relative path in config file.
But currently I'm pretty busy, will look into this later.

**Comment by kezoo** [comment]
We got a new option "fixedStylePath", please see if this suits your need. [427fcc77d52cff20d48a469ea0a927b8b27cbed1](https://github.com/kezoo/sprite-webpack-plugin/commit/427fcc77d52cff20d48a469ea0a927b8b27cbed1)
