### ISSUE TITLE
error when i install module sequelize and module express (nodejs) 

### ISSUE THREAD

**Issue by PhuongThaoNT** [kezoo/sprite-webpack-plugin#15]
here are my code and error: 
C:\mysql_demo>npm install mysql@2.10.2
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mysql@2.10.2"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mysql_demo\npm-debug.log
Help me!

**Comment by kezoo** [comment]
Currently only support Node < 6.0 due to lwip's compatibility, make sure your Node.js version is less than this
