### ISSUE TITLE
Does this support camelcase for naming?

### ISSUE THREAD

**Issue by Frada** [kezoo/sprite-webpack-plugin#16]
Does this support camelcase for naming? For both prefix and spriteName? If not, can I remove the dash for connector?

**Comment by kezoo** [comment]
There's a option "connector", it has four values to define a name:
1. "-", e.g.  "icon-name"
2. "_", e.g. "icon_name"
3. "capitalize", "IconName"  (Maybe you can choose this one)
4. "", e.g. "iconname"
