### ISSUE TITLE
Generated css file uses backslashes in background-image url path on Windows

### ISSUE THREAD

**Issue by kryogenic** [kezoo/sprite-webpack-plugin#3]
Here is an excerpt from the css file that webpack generates for me when I run it on windows:

```
.icon-no-icon {
  display: inline-block;
  background-position: 0px 0px;
  width: 20px;
  height: 20px;
  background-image: url('..\img\sprite-base.png');
}
```

These backslashes in the background-image url are interpreted as escape chars instead of slashes  (\i \s etc.) and the path turns out like this "..imgsprite-base.png". CSS will accept both double backslashes (\\) or forward slashes as far as I know.

I have a fork that is working for me: https://github.com/kryogenic/sprite-webpack-plugin. However I am not using less/sass or imports or any of the multi-folder options so I will leave the rest to you :smile:

**Comment by kezoo** [comment]
Sorry for that, I haven't tested this plugin on windows yet, will look into this in a short time.

**Comment by kezoo** [comment]
https://github.com/kezoo/sprite-webpack-plugin/commit/e9a117fc91231749f799c3b9f712f0d01fc5a100
