### ISSUE TITLE
Do not create 'sprites' folder

### ISSUE THREAD

**Issue by dortonway** [kezoo/sprite-webpack-plugin#8]
When I've configured plugin like so:

``` javascript
    new sprite({
      'source': __dirname + '/src/images/sprites/',
      'imgPath': __dirname + '/src/images/',
      'cssPath': __dirname + '/src/stylesheets/',
      'multiFolders': true
    })
```

Plugin generated sprites in '/src/images/sprites/'. On the first server load it worked, but on the second plugin thought that sprite image is usual image and tried to compile it to new sprite too (among appropriate images) and I got an error ''Pasted image exceeds dimensions of base image sprites".

I think, that this problem may happen to other people so I suggest use 'imgPath' path as is and do not create folder 'sprites' in him.

**Comment by kezoo** [comment]
I see, It seems that you put the source dir and generated images dir under the same directory, really have not thought about this condition yet.
I supposed they should be in two different directories, like this: /root/src/source and /root/src/images.
But anyway I will recheck this in the future updates, thanks for the information.

**Comment by kezoo** [comment]
https://github.com/kezoo/sprite-webpack-plugin/commit/e9a117fc91231749f799c3b9f712f0d01fc5a100
