### ISSUE TITLE
Add support for 'exclude' parameter

### ISSUE THREAD

**Issue by devlato** [kezoo/sprite-webpack-plugin#9]
Hi! 

It would be great to have an 'exclude' option to excude some directories from the sprite set.

**Comment by kezoo** [comment]
Your source directory is just what meant to be generated sprites, if there are some items you don't want them to, then just simply don't put them into that directory. 
I still don't understand what exactly your problem is.

**Comment by kezoo** [comment]
I will consider this at a later time
